name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v3
    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Build apk
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.1'
        channel: 'stable'
        cache: true
        cache-key: flutter # optional, change this to force refresh cache
        cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path
        architecture: x64 # optional, x64 or arm64
    - run: flutter pub get
    - run: flutter build apk
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: build/app/outputs/flutter-apk/*.apk
